### PR TITLE
Create chepy_iocextract.py

### PR DESCRIPTION
**Pull request by geekscrapy**
A simple ioc extract plugin using the iocextract library. Appreciate there is already an extract ips, urls plugins, however this extracts defanged IOCs

### CODE REVIEW

**Comment by securisec** [comment]
Thanks for the pull request! This is great! But there are some caveats to it. 

- The only thing that chepy did not extract from what   - iocextract extracts is hashes (i will add this to core)
  - the extract yara didnt work when i tested with the test.pcapng
  - the urls extracted from the pcap file was not defanged. 
- chepy already supports refang and defang

#### Suggestions for future pull requests
- Making the method name `iocextract` is bad news because it can potentially create a  namespace conflict. It is better to name it something like `extract_ioc`. 
- Follow the Chepy documentation guidelines from other modules. The reason why this plugin doesnt offer autocomplete is because Chepy cannot parse the docstrings in its current format
- When a file is read into chepy, it is either read as bytes or strings. If a binary file is read, it will read it as bytes. This will fail with iocextract which works with strings. In this case, it is better to make [this line](https://github.com/securisec/chepy_plugins/pull/1/commits/248f29a3a5d459d48c3f8eff11412201aea15888#diff-25ffd40d18431f1b707032ab91e468e0R24) `text_blob = self._convert_to_str()` which will make sure that the method is working with the right data type. 
- The `types` argument is not checked for validity, and seems unnessasry. For example, if user sets type as `foo`, it will throw an error. Instead, the types should not be user controlled and the method should loop over it and return a dictionary. If the user wants to pull only specific things, they can do so already in chepy. 
- Instead of concatanating lists, it is better to return a dict instead. this allows for better manupulation of the data by chepy after this plugin runs. If it is a dict, then the data can be pulled by `get_by_key` as an example. 
- Include tests for your pull requests. Try to use an existing test file from the core chepy repo for your tests. Tests should be submitted to the tests directory in plugins repo. 

## What would be a great idea for a pull request?
- I would appreciate a plugin that can generate yara rules for the data in state. That would make a fantastic pull request.

**Comment by geekscrapy** [comment]
Thanks, I'd prefer if you kept the pull request open if you want me to fix the issues you highlighted? I will address the points in your order:

- I contemplated using the inbuilt extract options instead of building another, except iocextract does one key thing the inbuilts don't, and that is our is able to extract _defanged_ IOCs. This is a common thing when collecting IOCs.
- It cannot extract yara signatures from pcap? This is impossible? How did you test this?
- I purposefully made IOCs fanged as it would be up to the user if they want them fanged or defanged. Maybe I'll take out the argument and let the library decide.
- I'm aware that chepy does de/fang, I use it lot. It's just another option I wanted to expose to the user.
- Naming the plugin after the library it uses at its core and is published on pip as such, is probably the best naming schema? I don't see how `extract_ioc` gets around this?
- Yup, my bad, I literally use chepy it as a library and forgot about the cli...!
- Again, yes, I assumed text, will fix (and my other internal plugins...)
- Yup, I'll get it to be checked. By defining the type to be extracted it may speed up the function and also provide the user a guaranteed output. But yes, if providing a dict as output is acceptable then this is fine.
- As above
- Yup, didn't think about this! My bad

- l'll open a new issue to discuss 🙂

**Comment by securisec** [comment]
I was testing against the test.pcapng that is in the chepy repo under tests. it was failing miserably on that pcap, and that pcap really isnt a crafted pcap with bad headers or something. Thats what I found odd about iocextract. 

About the naming, the reason why i say to use `extract_ico` vs `iocextract` is because when the parser parses the plugins, and i end up using isoextract in core one day, it will get confused. Also, `extract_*` keeps with the naming conventions I have in place for most of the chepy methods. 

I closed the pull request because as a personal plugin, this plugin is great, but it is not adding a ton of new functionality to existing features. I did integrate the extract hash in todays release `2.2.1` along with now showing in the cli when something is a plugin method, vs when something is a core method vs when something is a cli method.

**Comment by geekscrapy** [comment]
Ok, thanks, to clarify, iocextract doesn't work with binary files (like pcaps), just text blocks.

**Pull request closed without merging**
